name: app_dna_oficial
description: O melhor aplicativo de incorporadora e imobiliária do Brasil

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  video_player: ^2.4.2
  google_maps_flutter: ^2.1.6
  url_launcher: ^6.0.20


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.9.3


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/IconeDNA.png"
  remove_alpha_ios: true
  adaptative_icon_background: "#46b346"
  adaptative_icon_foreground: "assets/logo dna@4x.png"


flutter:
  uses-material-design: true

  assets:
     - assets/
     - assets/CaminhoDasAguas/
     - assets/ChacarasAM/
     - assets/BotaoAcompanharObra/
     - assets/Fundos/
     - assets/Icones/
     - assets/Localizacao/
     - assets/NovasFotos/
     - assets/ParaisoDosLagos/
     - assets/Projeto/

  fonts:
   - family: Poppins-ExtraBold
     fonts:
        - asset: assets/fonts/Poppins-ExtraBold.ttf

   - family: Poppins-Bold
     fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

